import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
const inter = Inter({ subsets: ['latin'] })
import TasksContext from '@/context/TasksContext'


export const metadata = {
  title: 'Super ToDo List',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Navbar />

        <TasksContext>

          {children}

        </TasksContext>
        
        </body>
    </html>
  )
}
